// Explanations for ETE questions (ete-q1 to ete-q100)
// Why each wrong answer is incorrect - concise 1-2 line explanations

export const eteExplanations: Record<string, string> = {
  // Unit 1: Advanced Processors and Technology
  "ete-q1": "GPUs use thousands of small cores for parallel visual computations, not for general data storage.",
  "ete-q2": "pinMode() is the correct ESP32 function to set GPIO pin mode; digitalMode() doesn't exist.",
  "ete-q3": "WiFi.begin() is the correct ESP32 API to initiate Wi-Fi connection; WiFi.connect() is not valid.",
  "ete-q4": "The Control Unit handles instruction sequencing; the ALU performs arithmetic and logic operations.",
  "ete-q5": "setup() runs exactly once at power-up; loop() is called repeatedly after setup completes.",
  "ete-q6": "Raspberry Pi OS is a full desktop OS that doesn't support ESP32 development like Arduino IDE does.",
  "ete-q7": "digitalWrite(4, HIGH) turns the LED on and it stays on because loop() is empty — no toggling logic exists.",
  "ete-q8": "WiFi.h must be included for WiFi functions; ESP32.h is for generic ESP32-specific features.",
  "ete-q9": "Supervised learning requires labeled input-output pairs; unsupervised learning finds hidden patterns without labels.",
  "ete-q10": "Unsupervised learning (like clustering) finds hidden patterns without labeled data, unlike supervised learning.",
  "ete-q11": "Naive Bayes is a probabilistic classifier, not typically used in reinforcement learning's trial-and-error model.",
  "ete-q12": "The qubit (quantum bit) is the fundamental unit of quantum computing, not the classical bit.",
  "ete-q13": "Superposition allows a qubit to exist in both 0 and 1 states simultaneously, enabling quantum parallelism.",
  "ete-q14": "Entanglement is a quantum phenomenon linking qubit states; superposition is a different principle.",
  "ete-q15": "The qubit is the foundation of quantum computing's exponential computational power over classical bits.",
  "ete-q16": "Quantum cryptography is a direct application of quantum computing principles for secure communication.",
  "ete-q17": "The bit (binary digit) is the fundamental unit of classical information, not the byte.",
  "ete-q18": "When WiFi.begin() fails on ESP32, it returns a status code — error codes are used, not the value 1.",
  "ete-q19": "Basic calculations (like a calculator) don't require AI; AI involves learning, reasoning, and decision-making.",
  "ete-q20": "GPUs excel at parallel processing like image rendering, not at general-purpose sequential tasks like CPUs.",

  // Unit 2: Smart Manufacturing
  "ete-q21": "SMT (Surface Mount Technology) largely replaced THT (Through-Hole Technology) for compact electronic devices.",
  "ete-q22": "SMT (Surface Mount Technology) places components directly on the PCB surface without leads through holes.",
  "ete-q23": "SMT allows higher component density and component placement on both sides of the PCB compared to through-hole.",
  "ete-q24": "In SMD sizing, 0603 means 0.06in × 0.03in (1.6mm × 0.8mm) — dimensions are in hundredths of an inch.",
  "ete-q25": "DFM (Design for Manufacturability) check evaluates all design specifications for production readiness.",
  "ete-q26": "A mechanical fixture called a guide plate (or clamp) holds the PCB during solder paste printing.",
  "ete-q27": "AOI (Automated Optical Inspection) efficiently inspects larger PCB batches using machine vision systems.",
  "ete-q28": "Cobots (collaborative robots) enable safe human-robot teamwork in smart manufacturing environments.",
  "ete-q29": "Robots in smart manufacturing perform pick-and-place, assembly, welding, painting, and precision machining.",
  "ete-q30": "Green manufacturing addresses growing e-waste by adopting sustainable, eco-friendly production processes.",
  "ete-q31": "WEEE (Waste Electrical and Electronic Equipment) is the EU directive governing electronic waste disposal.",
  "ete-q32": "RoHS and similar material declaration standards are used for certifying manufacturing material safety.",
  "ete-q33": "EPEAT evaluates products into Bronze, Silver, and Gold tiers of environmental performance.",
  "ete-q34": "EPEAT does not audit medical equipment categories under its product certification framework.",
  "ete-q35": "KiCad is a popular open-source PCB design tool used in open-source hardware development.",
  "ete-q36": "SkyWater 130nm is an example of an open-source PDK (Process Design Kit) for chip fabrication.",
  "ete-q37": "KiCad is used for open-source circuit simulation and PCB design, not just schematic capture.",
  "ete-q38": "Articulated robots with multiple joints perform complex 3D movements like welding, painting, and machining.",
  "ete-q39": "SCARA robots are mainly used for pick-and-place, assembly, and precision operations in manufacturing.",
  "ete-q40": "AMR (Autonomous Mobile Robots) use sensors to navigate factory floors independently without fixed paths.",

  // Unit 3: Next Generation Telecom
  "ete-q41": "NGN (Next Generation Network) architecture has 4 layers: transport, control, service, and application.",
  "ete-q42": "The management interface in NGN is for administration only and does not support media interaction.",
  "ete-q43": "OTN (Optical Transport Network) supports bitrates up to 100 Gbps and beyond per wavelength channel.",
  "ete-q44": "5.5G (5G-Advanced) builds upon 5G standards as defined by 3GPP Release 18 for enhanced capabilities.",
  "ete-q45": "NGN layers include the transport layer, service/control layer, and application/content layer.",
  "ete-q46": "CDF (Content Delivery Function) in NGN operates as part of the service/control layer.",
  "ete-q47": "Media Gateways are located in the transport layer of NGN architecture for media conversion.",
  "ete-q48": "TDMA (Time Division Multiple Access) is the multiplexing scheme used in 3G mobile networks.",
  "ete-q49": "FM Broadcast operates in the 88–108 MHz frequency range worldwide.",
  "ete-q50": "MPLS label header is 32 bits: 20-bit label, 8-bit TTL, 3-bit TC field, and 1-bit bottom-of-stack.",
  "ete-q51": "STM-1 carries 8000 frames per second at 155.52 Mbps; each frame time is 125 μs.",
  "ete-q52": "EXP (Experimental) bits in MPLS are reserved for experimental or quality-of-service marking purposes.",
  "ete-q53": "5G theoretical peak data speeds can reach up to 10 Gbps under ideal conditions.",
  "ete-q54": "SDH (Synchronous Digital Hierarchy) is the international fiber-optic transmission standard.",
  "ete-q55": "TTL (Time To Live) in an MPLS label is an 8-bit field that prevents packets from looping indefinitely.",
  "ete-q56": "In FTTH architecture, telemedicine is classified as an enhanced Tier-3 service requiring high bandwidth.",
  "ete-q57": "OLT (Optical Line Terminal) is critical in PON (Passive Optical Network) fiber-to-the-home architecture.",
  "ete-q58": "OLT's primary function is to manage and coordinate multiple ONUs in the PON network.",
  "ete-q59": "The protection scheme in OTN is defined by network management system (NMS) provisioning.",
  "ete-q60": "SDH provides synchronous multiplexing, clock synchronization, and network management features.",

  // Unit 4: IIoT and Immersive Technologies
  "ete-q61": "The perception layer (network layer) in IoT handles data transmission between devices and the internet.",
  "ete-q62": "Physical system monitoring is a valid CPS function — the option incorrectly claiming otherwise is wrong.",
  "ete-q63": "Cloud platforms like AWS IoT Core provide specialized services for IoT data visualization.",
  "ete-q64": "Industry 5.0 focuses on human-machine collaboration and personalization over full automation.",
  "ete-q65": "MQTT is a lightweight publish-subscribe protocol designed for IoT; HTTP is too heavyweight.",
  "ete-q66": "AR (Augmented Reality) overlays digital information onto the real world in real-time.",
  "ete-q67": "Precision farming is an IoT application; desktop publishing has no connection to IoT.",
  "ete-q68": "Industry 4.0 introduced automation and computers; Industry 3.0 introduced electronics and IT.",
  "ete-q69": "AWS (Amazon Web Services) leads in AI and data analytics among major cloud providers.",
  "ete-q70": "Extended Reality (XR) encompasses VR (Virtual Reality), AR (Augmented Reality), and MR (Mixed Reality).",
  "ete-q71": "IIoT applies IoT technologies specifically to industrial environments for monitoring and control.",
  "ete-q72": "Human-centric design and sustainability distinguish Industry 5.0 from Industry 4.0's full automation focus.",
  "ete-q73": "Spatial Mapping creates 3D digital representations of physical environments for AR/VR applications.",
  "ete-q74": "IoT improves manufacturing through real-time monitoring, predictive maintenance, and process automation.",
  "ete-q75": "Desktop publishing is unrelated to Industry 4.0's smart manufacturing and cyber-physical systems.",
  "ete-q76": "The middleware layer in a 5-layer IoT architecture provides communication and integration between layers.",
  "ete-q77": "Industry 5.0 aims to augment human workers with cobots, unlike Industry 4.0's push toward full automation.",
  "ete-q78": "In Industry 5.0, the collaboration layer is at the core where humans and cobots work together.",
  "ete-q79": "Mass production focus is excluded from Industry 5.0, which prioritizes customization and sustainability.",
  "ete-q80": "Google Cloud IoT is chosen for predictive maintenance due to its strong ML and data analytics capabilities.",

  // Unit 5: Drone Systems
  "ete-q81": "Multi-rotor drones (quadcopters) can hover precisely over small areas for aerial photography.",
  "ete-q82": "ESC (Electronic Speed Controller) precisely regulates motor speed for smooth drone flight control.",
  "ete-q83": "IMU (Inertial Measurement Unit) with accelerometer and gyroscope provides altitude and orientation data.",
  "ete-q84": "The gimbal stabilization system uses motors to maintain stable camera orientation during drone flight.",
  "ete-q85": "DGCA categorizes Indian airspace into Red (no-drone), Yellow (controlled), and Green (free) zones.",
  "ete-q86": "DGCA (Directorate General of Civil Aviation) is India's regulatory authority for drone licensing.",
  "ete-q87": "All drones except Nano category (<250g) must be registered on India's Digital Sky platform.",
  "ete-q88": "The Power Distribution Board (PDB) routes electrical power from battery to ESCs and other components.",
  "ete-q89": "Fixed-wing drones can fly for hours and cover large areas, ideal for mapping farmland over several hours.",
  "ete-q90": "Heavy-lift octocopters with multiple rotors can deliver substantial payloads to remote areas.",
  "ete-q91": "VTOL (Vertical Take-Off and Landing) drones suit vaccine delivery to villages with limited infrastructure.",
  "ete-q92": "Thermal imaging quadcopters are appropriate for flood rescue to locate people using heat signatures.",
  "ete-q93": "Agricultural drones (often multi-rotor) are designed for crop health monitoring and precision spraying.",
  "ete-q94": "Motor vibration and red LED during pre-flight may indicate motor imbalance or ESC calibration failure.",
  "ete-q95": "Maximum discharge current = 2.2Ah × 25C = 55A; with a 3S battery, max power ≈ 610W.",
  "ete-q96": "Fixed-wing drones with thermal cameras provide long endurance for dense forest wildlife tracking.",
  "ete-q97": "VTOL drones combine multi-rotor precision with fixed-wing efficiency for medical supply delivery.",
  "ete-q98": "Surveillance drones require long endurance, thermal imaging, and stable flight for infrastructure monitoring.",
  "ete-q99": "ESC (Electronic Speed Controller) precisely regulates motor speed for stable payload transport.",
  "ete-q100": "Rural open areas up to 120m AGL without prior approval fall under India's Green Zone category.",
};
